### ISSUE TITLE
Current status

### ISSUE THREAD

**Issue by nshi** [dibyendumajumdar/nlopt4j#3]
Hi @dibyendumajumdar,

Apologies for creating an issue here because I can't find your contact info.

I have a project that I want to use NLopt on in Java and your repository came up as the only binding available. Since the last commit was in 2017, I wonder if you can speak to the status of the bindings a little bit. Is it still stable and can be used out of the box?

Really appreciate any information.

Thanks,

Ning

**Comment by dibyendumajumdar** [comment]
Hi, I haven't tested this with the latest nlopt - I would hope it works.

If you face problems, please let me know

**Comment by nshi** [comment]
Thank you for the prompt response. I will test it out.
